### ISSUE TITLE
starfarer.api.jar 源码

### ISSUE THREAD

**Issue by NyaamZ** [TruthOriginem/Starsector-096-Localization#24]
- 我是韩国人。我正在做 Starsectror 的韩语翻译。 你能分享 starfarer.api.jar starfarer_obf.jar 的源代码吗？如果可能，我也希望你能把 build.xml 等项目文件发给我。
shipsail00@naver.com

**Comment by jnxyp** [comment]
您好，感谢您对本项目的关注。作为玩家自发组织的非官方翻译项目，我们没有获得 starfarer_obf.jar 的源代码。当前的汉化是通过直接修改jar文件中的字节码实现的。至于 starfarer.api.jar 的源代码，可以在同目录下 starfarer.api.zip 中找到。

**Comment by NyaamZ** [comment]
谢谢您的答复。

> 您好，感谢您对本项目的关注。作为玩家自发组织的非官方翻译项目，我们没有获得 starfarer_obf.jar 的源代码。当前的汉化是通过直接修改jar文件中的字节码实现的。至于 starfarer.api.jar 的源代码，可以在同目录下 starfarer.api.zip 中找到。

谢谢您的答复。

**Comment by NyaamZ** [comment]
谢谢您的答复。
