### ISSUE TITLE
事件文本重复出现

### ISSUE THREAD

**Issue by osotoaoro** [TruthOriginem/Starsector-096-Localization#25]
![6Y8W6%7CH4X}F6T)J~$6B~4](https://github.com/TruthOriginem/Starsector-096-Localization/assets/49361493/5da3c47d-3def-4d5f-9746-d447a4b66dd3)

**Comment by jnxyp** [comment]
找到问题了，新版本把老的对话移动到另一行里了，但是由于平台上还残留有老的译文，所以把老的译文导入进原来那行里了，导致游戏bug。

修改了导入脚本，让其在原文为空时忽略译文数据。如果现在已经有译文数据了就删除。

经测试，bug已解决。
