### ISSUE TITLE
酒馆事件选项错位

### ISSUE THREAD

**Issue by osotoaoro** [TruthOriginem/Starsector-096-Localization#26]
![image](https://github.com/TruthOriginem/Starsector-096-Localization/assets/49361493/43fa633f-3fda-4310-a57b-c03507762f1e)

**Comment by jnxyp** [comment]
![image](https://github.com/TruthOriginem/Starsector-096-Localization/assets/16182688/20c6345e-ad7a-405c-b82b-e0a1e7f83df9)
已修复
