### ISSUE TITLE
para_tranz 错误？

### ISSUE THREAD

**Issue by NyaamZ** [TruthOriginem/Starsector-096-Localization#27]
你好 我就是上次和你联系的那个韩国人。
我用了 para_tranz，但我的 json 导出和重写只有 3 和 18。
不知道是有 bug 还是我用错了。

And can I use para tranz for Korean translation?
![bug1](https://github.com/TruthOriginem/Starsector-096-Localization/assets/43065065/0af14370-3a38-459a-9d79-793312ba5bc2)

**Comment by jnxyp** [comment]
您可以使用paratranz平台来进行韩语翻译，不过对于这个词条导出脚本，其中有部分代码仅针对中文设计，在处理韩语时可能出现问题。

至于无法导出jar词条的问题，请问您是直接将整个存储库克隆到本地，在没有做其他更改的情况下运行脚本，出现这种情况的吗？

如果需要进一步帮助可以通过邮箱与我联系： jinan.xyp@gmail.com

**Comment by jnxyp** [comment]
使用邮件进行后续沟通
