### ISSUE TITLE
眼魔DEM的高亮描述错位

### ISSUE THREAD

**Issue by osotoaoro** [TruthOriginem/Starsector-096-Localization#30]
![%MZEY%~6KR2YRMVKO~JTAVA](https://github.com/TruthOriginem/Starsector-096-Localization/assets/49361493/48ff1e7f-951c-4a89-a900-75767b347943)

**Comment by jnxyp** [comment]
请问这里具体的问题是？

**Comment by TruthOriginem** [comment]
> 请问这里具体的问题是？

汉化语序和原文语序做了调整，现在是颠倒过来的。

**Comment by 1847905557** [comment]
解决
