### ISSUE TITLE
废弃空间站 - 菜单选项前后词条不一致

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-096-Localization#32]
任意废弃空间站，第一次接入和后续再访问时使用的词条不同（不确定是不是算bug）
但选择不同的词条效果是一样的，并且没有额外的说明文本

第一次访问的菜单选项：
![4](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/2eeb8a13-a777-448d-a91c-3ee9b0e95348)

后续菜单选项：
![3](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/866ebd32-4c21-44ce-9227-c5f78bb36649)

**Comment by TruthOriginem** [comment]
是沉浸式内容，检查过货仓/舰船后会自动改变选项
