### ISSUE TITLE
无法执行突袭行动

### ISSUE THREAD

**Issue by N071** [TruthOriginem/Starsector-096-Localization#36]
![image](https://github.com/TruthOriginem/Starsector-096-Localization/assets/128023427/7038c320-2dc3-4723-88a1-802ae1295cd4)

我发现[Issue 19](https://github.com/TruthOriginem/Starsector-096-Localization/issues/19)提及了相同问题，而[回复](https://github.com/TruthOriginem/Starsector-096-Localization/issues/19#issuecomment-1763710684)说明问题已经解决，并关闭了该条Issue。

我发现我遇到的问题与Issue 19相同，并确认自己下载了最新版本的096前瞻汉化。我仍然遇到此问题。

很抱歉我不知道如何提供如同[此评论](https://github.com/TruthOriginem/Starsector-096-Localization/issues/19#issuecomment-1745573976)一样的报错信息。如果您无法复现这个问题，那么我很乐意继续跟进提供信息。

**Comment by N071** [comment]
如果你有阅读英语的能力，但是你觉得部分汉化能提高你的阅读速度：
在单独测试后，我发现你可以选择唯独不替换`starfarer.api.jar`，就不会出现无法执行突袭的问题，同时享受大部分汉化

**Comment by LukeWhyes** [comment]
在用汉化补丁覆盖原文件后玩了一段时间，遇到相同的情况后又单独用原本的starfarer.api.jar替换回去了，但是问题依然存在。更有意思的是，替换回去后汉化依然是完整的——相对于这个补丁版而言

**Comment by Gother233** [comment]
> 在用汉化补丁覆盖原文件后玩了一段时间，遇到相同的情况后又单独用原本的starfarer.api.jar替换回去了，但是问题依然存在。更有意思的是，替换回去后汉化依然是完整的——相对于这个补丁版而言

那说明你可能并没有真的替换成功

**Comment by LifeGamef** [comment]
> 写给遇到相同问题的人： 如果你有阅读英语的能力，但是你觉得部分汉化能提高你的阅读速度： 在单独测试后，我发现你可以选择唯独不替换`starfarer.api.jar`，就不会出现无法执行突袭的问题，同时享受大部分汉化

作为临时解决方法:
可以使用解压软件打开starfarer_obf.jar文件,在com/fs/starfarer/campaign/ui/marketinfo/路径下的GroundRaidTargetPickerDialog.class文件替换为原本的英文文件
此方法会让突袭界面退回英文并可以正常使用

**Comment by Deathfly** [comment]
已定位修复

**Comment by 1847905557** [comment]
当时虽然修复了，但并没有编译并更新到github上。关闭issue并不意味着修复本身会立刻被提供到最新版本里

**Comment by 1847905557** [comment]
晚些时候会推送带修复的汉化包
