### ISSUE TITLE
OpenAI && DeepL

### ISSUE THREAD

**Issue by 2233431914** [TruthOriginem/Starsector-096-Localization#37]
无意冒犯，请问为什么不使用DeepL或者OpenAI的api去翻译呢，现在AI翻译效果很好，并且也可以给它相应的语境和场景，这样翻译的效率只会大大的提高。

**Comment by 1847905557** [comment]
因为它翻得不好

**Comment by Deathfly** [comment]
我们已经尝试过使用AI辅助翻译，但结果并不理想。

AI训练材料主要基于网络上公布的翻译资料，对新闻和专业文章等风格和样式较为统一的文本翻译效果是不错。但对于独立游戏中这类原创性很高的虚构故事，由于没有既有翻译能很好的提供参考，因此AI并不能很好的完成这种任务。
