### ISSUE TITLE
角色技能 - 疑似未翻译完全的词条

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-096-Localization#5]
1. Neural Link技能下的描述，有旧的英文词条未删除
![Neural Link](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/cd70ae2d-96fa-49df-a2a3-b9da58b2ab33)

2. Polarized Armor技能下的描述，有一半是英文词条
![Polarized Armor](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/d3b3595b-4b6c-4583-be8a-633654f94baa)

**Comment by 1847905557** [comment]
解决
