### ISSUE TITLE
舰船数据 - 舰船系列描述词条未替换

### ISSUE THREAD

**Issue by ck1521** [TruthOriginem/Starsector-096-Localization#9]
示例如图：
![2](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/c3222df5-e453-4284-b741-7ae188b5aa08)

对比0.951：
![3](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/fad1b88d-85c5-49c4-a02e-042b51fb7bfd)

**Comment by ck1521** [comment]
存在此问题的原版船系列（截图来自0.951）
1. (P)  - 海盗改装系列
![P](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/fedb6155-daa7-4bc2-b088-81b38bb5d7b9)


2. (XIV) - 霸主14军团系列
![XIV](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/1a193c60-bfa6-406b-8ffc-f53a5bf81cd5)

3. (A) - 霸主民用船改装系列
![A](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/d4a97036-cdde-4969-8e73-6413e48741ef)

4. (H) - 霸主涂装系列
![H](https://github.com/TruthOriginem/Starsector-096-Localization/assets/10858385/7d357565-3d17-4c76-ac04-b17b9806ea8f)

**Comment by ck1521** [comment]
好像有问题的不是所有船，只是系列中的一部分（比如水牛(P)的文本就是对的，但是根除者(P)就有缺失）
并且有这些问题的船刚好船名也没汉化，应该可以这么区分

**Comment by TruthOriginem** [comment]
逐步替换中
